name: frame_flutter_translate_host
description: "Connects to Frame and streams audio from its microphone, which is sent through a local (on Host device) Whisper.cpp speech-to-text engine for direct Korean to English translation, and displays the translated text on the Frame display."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_whisper: ^0.1.6
  record: ^5.0.5
  buffered_list_stream: ^1.3.0
  logging: ^1.2.0
  simple_frame_app: ^0.0.7
  path_provider: ^2.1.2
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - packages/simple_frame_app/lua/battery.min.lua
    - packages/simple_frame_app/lua/data.min.lua
    - packages/simple_frame_app/lua/plain_text.min.lua
    - assets/frame_app.min.lua
    - assets/whisper-base.bin